[project]
name = "soda-ahk"
version = "2025.1.6.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = ["pyautogui>=0.9.54", "pywin32>=308"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
# All the following settings are optional:
where = ["."]                             # ["."] by default
include = ["*"]                           # ["*"] by default
exclude = ["test*", "scripts", ".vscode"] # empty by default

[tool.setuptools.package-data]
script_templates = ["*.ahk"]
resources = ["*.zip", "*.ps1", "*.dll", "*.ico", "*.exe", "*.json", "*.pdb"]

[dependency-groups]
dev = [
    "build>=1.2.2.post1",
    "twine>=6.0.1",
]

[project.scripts]
soda-ahk-cli = "ahk.main:main"
soda-ahk-cursor-cli = "ahk_cursor.main:main"

[project.gui-scripts]
soda-ahk = "ahk.main:main"
soda-ahk-cursor = "ahk_cursor.main:main"
